### ISSUE TITLE
ignore_pathsオプション

### ISSUE THREAD

**Issue by pooza** [pooza/zhacai#3]
```
growi:
  url: https://growi.example.com
  token: __YOUR_TOKEN__
  entries:
    - path: /user/pooza/curesta
      hook: https://mstdn.example.com/mulukhiya/webhook/xxxxxx
      ignore_paths:
        - /user/pooza/curesta
```
`/user/pooza/curesta` を無視できるように。
